### ISSUE TITLE
Problem with ASA Query and NullReferenceException

### ISSUE THREAD

**Issue by WizzardMaker** [arlotito/IotEdgePerf#10]
I'm trying to test my IoTEdge Device with this tool, but I have troubles with setting up the ASA Job and the receiving of messages.

The console app crashes because of a NullReferenceException when reading from the hub (it apparently receives the payload messages from the transmitter, but no ASA message)

What settings do I have to set for the ASA query?
I already set the input and output (renamed them in the query to my input and output aliases) and started the query
![image](https://user-images.githubusercontent.com/7768485/149122389-da57a8f9-048a-41df-af34-d3640ca6dc47.png)

**Comment by WizzardMaker** [comment]
We found out why the error message came
It wasn't clear that the created ASA job had to be directly added to the device as a module.

**Comment by arlotito** [comment]
Hi, maybe I misunderstand what you mean... but the ASA job should be deployed in the cloud, and not at the edge.
Would you mind detailing how you built your setup? Thanks!

**Comment by arlotito** [comment]
closed.
